{
   "no_index" : {
      "directory" : [
         "t",
         "inc"
      ]
   },
   "meta-spec" : {
      "version" : 1.4,
      "url" : "http://module-build.sourceforge.net/META-spec-v1.4.html"
   },
   "generated_by" : "ExtUtils::MakeMaker version 6.56",
   "distribution_type" : "module",
   "version" : "0.96",
   "name" : "AnyEvent-IRC",
   "author" : [
      "Robin Redeker <elmex@ta-sa.org>"
   ],
   "license" : "perl",
   "build_requires" : {
      "ExtUtils::MakeMaker" : 0
   },
   "requires" : {
      "Scalar::Util" : 0,
      "Test::More" : 0,
      "AnyEvent" : "5.111",
      "Object::Event" : "0.6",
      "common::sense" : 0,
      "Encode" : 0
   },
   "abstract" : "An event based IRC protocol client API",
   "configure_requires" : {
      "ExtUtils::MakeMaker" : 0
   }
}
