--- #YAML:1.0
name:               AnyEvent-IRC
version:            0.7
abstract:           An event system independend IRC protocol module
author:
    - Robin Redeker <elmex@ta-sa.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:       0
    Object::Event:  0.5
    Test::More:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
